version: "3"
services:
  golang-skeleton:
    image: golang_skeleton:1.2.9
    build:
      context: ..
      dockerfile: build/docker/golang/Dockerfile
    container_name: golang-project-skeleton
    tty: true
    restart: on-failure
    volumes:
      - ../:/usr/local/golang-dev/golang-project-skeleton
    working_dir: /usr/local/golang-dev/golang-project-skeleton
    networks:
      - golang_project_skeleton

networks:
  golang_project_skeleton:
    driver: bridge